### PR TITLE
3dmodels: added E73-2G4M08S1C nRF52840 module

### PR DESCRIPTION
**Pull request by badrbouslikhin**
#### **Title:**
Add 3D model for E73-2G4M08S1C nRF52840 module

#### **Description:**
This pull request adds a new 3D model for the E73-2G4M08S1C nRF52840 module to enhance the library's component offerings.

#### **Scope of change:**
This change is related to the 3D model.
Most is of the changes in the footprint data is KiCad's autoformat.

#### **Change detail:**

* File added: `3dmodels/nordic-lib-kicad-nrf52-modules.3dshapes/E73-2G4M08S1C.step`: Added new STEP file for the E73-2G4M08S1C nRF52840 module
* File changed: `footprints/nordic-lib-kicad-nrf52-modules.pretty/E73-2G4M08S1C.kicad_mod`: Linked 3D model to footprint

#### **Screenshots:**
Screenshot 2024-07-20 at 16 00 16

#### **Source of change or fix:**
N/A.

#### **Testing:**
None, my PCB will be manufactured soon.

#### **Checklist:**

- [X] My change follows the conventions of the library 
- [ ] My changes generate no new warnings
I couldn't run the check script, the following errors popped:
```
❯ ./lib_check.sh
./lib_check.sh: line 2: ./kicad-library-utils/klc-check/check_symbol.py: No such file or directory
./lib_check.sh: line 2: ./kicad-library-utils/klc-check/check_symbol.py: No such file or directory
./lib_check.sh: line 2: ./kicad-library-utils/klc-check/check_symbol.py: No such file or directory
./lib_check.sh: line 2: ./kicad-library-utils/klc-check/check_symbol.py: No such file or directory
./lib_check.sh: line 2: ./kicad-library-utils/klc-check/check_symbol.py: No such file or directory
./lib_check.sh: line 2: ./kicad-library-utils/klc-check/check_symbol.py: No such file or directory
./lib_check.sh: line 2: ./kicad-library-utils/klc-check/check_symbol.py: No such file or directory
./lib_check.sh: line 2: ./kicad-library-utils/klc-check/check_symbol.py: No such file or directory
./lib_check.sh: line 6: ./kicad-library-utils/klc-check/check_footprint.py: No such file or directory
./lib_check.sh: line 6: ./kicad-library-utils/klc-check/check_footprint.py: No such file or directory
./lib_check.sh: line 6: ./kicad-library-utils/klc-check/check_footprint.py: No such file or directory
./lib_check.sh: line 6: ./kicad-library-utils/klc-check/check_footprint.py: No such file or directory
./lib_check.sh: line 6: ./kicad-library-utils/klc-check/check_footprint.py: No such file or directory
./lib_check.sh: line 6: ./kicad-library-utils/klc-check/check_footprint.py: No such file or directory
./lib_check.sh: line 6: ./kicad-library-utils/klc-check/check_footprint.py: No such file or directory
./lib_check.sh: line 6: ./kicad-library-utils/klc-check/check_footprint.py: No such file or directory
./lib_check.sh: line 6: ./kicad-library-utils/klc-check/check_footprint.py: No such file or directory
./lib_check.sh: line 6: ./kicad-library-utils/klc-check/check_footprint.py: No such file or directory
./lib_check.sh: line 6: ./kicad-library-utils/klc-check/check_footprint.py: No such file or directory
./lib_check.sh: line 6: ./kicad-library-utils/klc-check/check_footprint.py: No such file or directory
./lib_check.sh: line 6: ./kicad-library-utils/klc-check/check_footprint.py: No such file or directory
./lib_check.sh: line 6: ./kicad-library-utils/klc-check/check_footprint.py: No such file or directory
./lib_check.sh: line 6: ./kicad-library-utils/klc-check/check_footprint.py: No such file or directory
./lib_check.sh: line 6: ./kicad-library-utils/klc-check/check_footprint.py: No such file or directory
./lib_check.sh: line 6: ./kicad-library-utils/klc-check/check_footprint.py: No such file or directory
```

### CODE REVIEW

**Comment by hlord2000** [comment]
Thanks for the contribution, could you share where the 3D model came from? did you create it yourself? Thanks!

**Comment by badrbouslikhin** [comment]
It's an extract from JLCPCB's EasyEDA models (using [easyeda2kicad.py](https://github.com/uPesy/easyeda2kicad.py)).
I didn't check the licence to be honest.

**Comment by hlord2000** [comment]
> It's an extract from JLCPCB's EasyEDA models (using [easyeda2kicad.py](https://github.com/uPesy/easyeda2kicad.py)). I didn't check the licence to be honest.

The model will have to be created from scratch or released by the rights holder for it to be integrated into the library, unfortunately

**Comment by badrbouslikhin** [comment]
I understand.
I'll see if I have time to do it later.

**Pull request closed without merging**
